security:
    encoders:
        SIS\AdminBundle\Entity\User:
            algorithm: sha512
            encode-as-base64: true
            iterations: 10

    providers:
        user_db:
            entity: { class: SIS\AdminBundle\Entity\User, property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/admin/login$
            security: false

        secured_area:
            pattern:    ^/admin
            form_login:
                login_path: /admin/login
                check_path: /admin/login_check
                default_target_path: /admin/sismo/
                always_use_default_target_path: true
            logout:
                path: /admin/logout
                target: /

    access_control:
      - { path: ^/admin/user/, roles: ROLE_ADMIN }
      - { path: ^/, roles: [ROLE_USER, ROLE_ADMIN] }
