<?php

namespace SIS\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TemblorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TemblorRepository extends EntityRepository
{
}