parameters:
#    sis_admin.example.class: SIS\AdminBundle\Example

services:
#    sis_admin.example:
#        class: %sis_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
